name: AFK
main: TheRealKizu\AFK\Main
api: [3.0.0]
version: 1.0.0
author: TheRealKizu
description: Simple /afk plugin for PocketMine

commands:
  afk:
    description: AFK command
    permission: afk.cmd

permission:
  afk.cmd:
    default: true
