---
# Main Configuration File
# AFK by Assassiner354
#     ___  ______  _   __
#    / _ \ |  ___|| | / /
#   / /_\ \| |_   | |/ /
#   |  _  ||  _|  |    \
#   | | | || |    | |\  \
#   \_| |_/\_|    \_| \_/

#Disables movement while afk
# NOTE:DEPRECATED FEATURE! DOESNT WORK ANYMORE! WILL BE REMOVED IN THE FUTURE
no-move: true

#Disables chatting while afk
no-chat: true

...
